version: "3"
services:
  metaland-map:
    build: .
    container_name: metaland-map
    restart: unless-stopped
    ports:
      - 8003:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config.json:/config.json